// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZIeLRI6Mas_E_UhzmSdprRDSIGG2Fkxo',
    appId: '1:926846771802:web:605cf558e8197ac2336e63',
    messagingSenderId: '926846771802',
    projectId: 'socialwall-fcc35',
    authDomain: 'socialwall-fcc35.firebaseapp.com',
    storageBucket: 'socialwall-fcc35.appspot.com',
    measurementId: 'G-MYWJG6TGMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl_czAKjvT4ItrTnhNBdtg3f0kuSSurvQ',
    appId: '1:926846771802:android:4a898c1348d200c0336e63',
    messagingSenderId: '926846771802',
    projectId: 'socialwall-fcc35',
    storageBucket: 'socialwall-fcc35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANGR-l21mc-uXzWFRUzm_bQSOtAV72Dto',
    appId: '1:926846771802:ios:155e29cf8fcf10d4336e63',
    messagingSenderId: '926846771802',
    projectId: 'socialwall-fcc35',
    storageBucket: 'socialwall-fcc35.appspot.com',
    iosBundleId: 'com.example.socialwall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANGR-l21mc-uXzWFRUzm_bQSOtAV72Dto',
    appId: '1:926846771802:ios:ab98b5596e073306336e63',
    messagingSenderId: '926846771802',
    projectId: 'socialwall-fcc35',
    storageBucket: 'socialwall-fcc35.appspot.com',
    iosBundleId: 'com.example.socialwall.RunnerTests',
  );
}
